version: '3.8'

services:
  app:
    build: ./telephony_api
    ports:
      - 5000:5000
    volumes:
      - ./telephony_api/src:/app/src
    depends_on:
      - db

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=telephony_api
      - POSTGRES_PASSWORD=telephony_api
      - POSTGRES_DB=telephony_api_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:    